//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class even
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ThumbImg { get; set; }
        public string BannerImg { get; set; }
        public string Description { get; set; }
        public string HomeUrl { get; set; }
        public string Param { get; set; }
        public Nullable<int> MinCount { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public Nullable<int> CheckInCount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
