//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_comment
    {
        public int Id { get; set; }
        public int GoodsId { get; set; }
        public System.DateTime Time { get; set; }
        public string Author { get; set; }
        public Nullable<sbyte> Score { get; set; }
        public string Content { get; set; }
    }
}
