//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_img
    {
        public int Id { get; set; }
        public int GoodsId { get; set; }
        public bool ImgType { get; set; }
        public int ImgOrder { get; set; }
        public string ImgPath { get; set; }
    }
}
