//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class good
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public string Name { get; set; }
        public int ClassificationId { get; set; }
        public float OriginalPrice { get; set; }
        public float RetailPrice { get; set; }
        public string ThumbImg { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public int SellQuantity { get; set; }
        public bool Status { get; set; }
    }
}
