//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int StoreId { get; set; }
        public int GoodsId { get; set; }
        public string GoodsName { get; set; }
        public string GoodsShortDesc { get; set; }
        public float Price { get; set; }
        public int Count { get; set; }
        public string ThumbImg { get; set; }
    }
}
