//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime OrderTime { get; set; }
        public string OrderNumber { get; set; }
        public float TotalPrice { get; set; }
        public int PayPoint { get; set; }
        public float PayAmount { get; set; }
        public bool PaymentType { get; set; }
        public bool ExpressType { get; set; }
        public string ExpressNumber { get; set; }
        public float ExpressPrice { get; set; }
        public string AddressId { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
    }
}
