//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class recommendation
    {
        public int Id { get; set; }
        public Nullable<bool> Type { get; set; }
        public string BannerImg { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
    }
}
