//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STSCEntities : DbContext
    {
        public STSCEntities()
            : base("name=STSCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<classification> classifications { get; set; }
        public virtual DbSet<even> evens { get; set; }
        public virtual DbSet<event_user> event_user { get; set; }
        public virtual DbSet<good> goods { get; set; }
        public virtual DbSet<goods_comment> goods_comment { get; set; }
        public virtual DbSet<goods_img> goods_img { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<recommendation> recommendations { get; set; }
        public virtual DbSet<store_user> store_user { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_address> user_address { get; set; }
        public virtual DbSet<user_favorite> user_favorite { get; set; }
        public virtual DbSet<user_points> user_points { get; set; }
        public virtual DbSet<store> stores { get; set; }
    }
}
