//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSC.Service.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_points
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int Point { get; set; }
        public int ReasonCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
    }
}
